mindmap
  root((Consciousness Theories))
    Neuroscientific
      Global Workspace
      Recurrent Processing
      Attention Schema
      Higher-Order Thought
    Information
      Integrated Information Theory
      Computationalism
      Bayesian Brain
    Philosophical
      Dualism
      Physicalism
      Functionalism
      Illusionism
      Panpsychism
    Embodied
      Enactive
      Embodied Cognition
    Physical
      Quantum Theories
      Emergentism
